name: Expo CI

on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and build EAS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn policies set-version 1.22.17
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build on EAS
        run: eas build --platform android --non-interactive
